{% set version = "2.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-readods
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/readODS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readODS/readODS_{{ version }}.tar.gz
  sha256: 2e67997806d71cc37401975dbdf1e1f0c04140afe218d03637dd6172b54f3476

build:
  number: 0
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cellranger
    - r-minty
    - r-stringi
    - r-tibble
    - r-vctrs >=0.4.2
    - r-zip
  run:
    - r-base
    - r-cellranger
    - r-minty
    - r-stringi
    - r-tibble
    - r-vctrs >=0.4.2
    - r-zip

test:
  commands:
    - $R -e "library('readODS')"           # [not win]
    - "\"%R%\" -e \"library('readODS')\""  # [win]

about:
  home: https://github.com/ropensci/readODS
  license: GPL-3.0-only
  summary: Import ODS (OpenDocument Spreadsheet) into R as a data frame. Also support writing data frame into ODS file.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar

# The original CRAN metadata for this package was:
# Package: readODS
# Type: Package
# Title: Read and Write ODS Files
# Version: 1.6.7
# Date: 2018-11-25
# Author: Gerrit-Jan Schutten, Chung-hong Chan, Thomas J. Leeper and other contributors
# Maintainer: Chung-hong Chan <chainsawtiney@gmail.com>
# Contact: https://github.com/chainsawriot/readODS/
# Description: Import ODS (OpenDocument Spreadsheet) into R as a data frame. Also support writing data frame into ODS file.
# Imports: xml2 (>= 1.0.0), cellranger, readr, stringi
# Suggests: dplyr, testthat, datasets
# License: GPL-3
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-11-26 02:04:27 UTC; chainsaw
# Repository: CRAN
# Date/Publication: 2018-11-26 05:40:03 UTC
# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
